#!/bin/bash

docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker rmi -f $(docker images -aq)
docker system prune -f
apt-get purge -y docker-engine docker docker.io docker-ce docker-compose docker-ce-cli containerd.io
apt-get autoremove -y --purge docker-engine docker docker.io docker-ce docker-compose
rm -rf /var/lib/docker
